{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.dokkacov",
    "module": "dokkacov",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "gxirzhgp2nhsti57pusxiykrwe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkacov-0.1.jar",
          "url": "dokkacov-0.1.jar",
          "size": 37902,
          "sha512": "f330fdbce9818505fb367a0e5d79979cabad1697af139f3abbb5061d168c781bb78cdb1637f668181b5eb0b9160ab13511eda0097ea88e17f35f6a3a2a906c7a",
          "sha256": "d71084f97eacbf6e3e865d4cbf8215851fa3ef5b248090609e56b50d3bd74290",
          "sha1": "9bb7f4a734485277ac1b84712958827cf5f489a6",
          "md5": "5e2764da4850718075420d9cdf668b2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        }
      ],
      "files": [
        {
          "name": "dokkacov-0.1.jar",
          "url": "dokkacov-0.1.jar",
          "size": 37902,
          "sha512": "f330fdbce9818505fb367a0e5d79979cabad1697af139f3abbb5061d168c781bb78cdb1637f668181b5eb0b9160ab13511eda0097ea88e17f35f6a3a2a906c7a",
          "sha256": "d71084f97eacbf6e3e865d4cbf8215851fa3ef5b248090609e56b50d3bd74290",
          "sha1": "9bb7f4a734485277ac1b84712958827cf5f489a6",
          "md5": "5e2764da4850718075420d9cdf668b2c"
        }
      ]
    }
  ]
}
