{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.11/kohomology-0.11.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.11.jar",
          "url": "kohomology-jvm-0.11.jar",
          "size": 1346324,
          "sha512": "efb63ba3c32488e86cb6ac6f777ef3f1b5808f6c64a12610be8cc2f9736ddd12f90f545b3dc814525ab548bad7ba2c509afb0aca346977c012287e7841f24361",
          "sha256": "bd461986c25de9f22a79d98f1f33135c0412f43a5907a4b53bfb574110e8eebc",
          "sha1": "d392795aaa2019c347116e1a39aa95a97f22fd35",
          "md5": "acf10a4ee8e693589e6649d88e54a487"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.11.jar",
          "url": "kohomology-jvm-0.11.jar",
          "size": 1346324,
          "sha512": "efb63ba3c32488e86cb6ac6f777ef3f1b5808f6c64a12610be8cc2f9736ddd12f90f545b3dc814525ab548bad7ba2c509afb0aca346977c012287e7841f24361",
          "sha256": "bd461986c25de9f22a79d98f1f33135c0412f43a5907a4b53bfb574110e8eebc",
          "sha1": "d392795aaa2019c347116e1a39aa95a97f22fd35",
          "md5": "acf10a4ee8e693589e6649d88e54a487"
        }
      ]
    }
  ]
}
