{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug/0.1/kococo-debug-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "oihpmjuen5d6rlqsaveqwct6su"
    }
  },
  "variants": [
    {
      "name": "jsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jslegacy-0.1.jar",
          "url": "kococo-debug-js-0.1.jar",
          "size": 2681,
          "sha512": "8a72394452512cb15c68948cbf109ca076fd428f34b945f8faf7f91f721e4d62c7657398cd2181adbada41bf2b4621a515e14d5d58b0581a2c92d5019042a13d",
          "sha256": "87f3342587cdf1b08775c6230fcec2e6ddbf909688d5f3b9570579760a3bbb39",
          "sha1": "29416d35f480d99ecb2a234f040f123a89140fe8",
          "md5": "56538ade703863b4795df916b4d881c0"
        }
      ]
    },
    {
      "name": "jsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jslegacy-0.1.jar",
          "url": "kococo-debug-js-0.1.jar",
          "size": 2681,
          "sha512": "8a72394452512cb15c68948cbf109ca076fd428f34b945f8faf7f91f721e4d62c7657398cd2181adbada41bf2b4621a515e14d5d58b0581a2c92d5019042a13d",
          "sha256": "87f3342587cdf1b08775c6230fcec2e6ddbf909688d5f3b9570579760a3bbb39",
          "sha1": "29416d35f480d99ecb2a234f040f123a89140fe8",
          "md5": "56538ade703863b4795df916b4d881c0"
        }
      ]
    },
    {
      "name": "jsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jsir-0.1.klib",
          "url": "kococo-debug-js-0.1.klib",
          "size": 2788,
          "sha512": "6a09935778aab9325e6f67e6f39fa76e739f435151e010ee4741e8209d4704cb20ff2b677d7ba63ad37c0a590fba110af670a6694e32f802f347e8576e6e309c",
          "sha256": "e25bf071241145f11e6f0ae50cf99bdbebdf19fb424f6366940a0de0b4d41eef",
          "sha1": "cc22bb882563592e63eb0c754b30397bd941796f",
          "md5": "672268e60600ad65ac639e3fddf9e2e7"
        }
      ]
    },
    {
      "name": "jsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jsir-0.1.klib",
          "url": "kococo-debug-js-0.1.klib",
          "size": 2788,
          "sha512": "6a09935778aab9325e6f67e6f39fa76e739f435151e010ee4741e8209d4704cb20ff2b677d7ba63ad37c0a590fba110af670a6694e32f802f347e8576e6e309c",
          "sha256": "e25bf071241145f11e6f0ae50cf99bdbebdf19fb424f6366940a0de0b4d41eef",
          "sha1": "cc22bb882563592e63eb0c754b30397bd941796f",
          "md5": "672268e60600ad65ac639e3fddf9e2e7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    }
  ]
}
