{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotex/0.1/kotex-0.1.module",
    "group": "me.shun",
    "module": "kotex",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "kotex-js-0.1.jar",
          "url": "kotex-js-0.1.jar",
          "size": 27873,
          "sha512": "3b65a0caa4960066dd7305e04c661d4c308efef7625375ad8453dc44a9a1f04944bad22d9782a43e5dd15580bd31deb2406dd3789de6edd71e4c85d4d08d9b6a",
          "sha256": "15e67a8854c51b9973c342d14019a785279c72a902d5622cb1280e490be88097",
          "sha1": "efce043cd4453944e2fb896b20a871f15c8759d5",
          "md5": "6f09b16b08e66b3fc4be583fd043c07e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "kotex-js-0.1.jar",
          "url": "kotex-js-0.1.jar",
          "size": 27873,
          "sha512": "3b65a0caa4960066dd7305e04c661d4c308efef7625375ad8453dc44a9a1f04944bad22d9782a43e5dd15580bd31deb2406dd3789de6edd71e4c85d4d08d9b6a",
          "sha256": "15e67a8854c51b9973c342d14019a785279c72a902d5622cb1280e490be88097",
          "sha1": "efce043cd4453944e2fb896b20a871f15c8759d5",
          "md5": "6f09b16b08e66b3fc4be583fd043c07e"
        }
      ]
    }
  ]
}
