{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-release/0.1/kococo-release-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-release",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "y5wcifjiunac3hakjkowrfxxna"
    }
  },
  "variants": [
    {
      "name": "jsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jslegacy-0.1.jar",
          "url": "kococo-release-js-0.1.jar",
          "size": 2678,
          "sha512": "ba0dfe1c6a197f46725769190a801fb968ca08d4508dadc1f7c5c3980cfae3789d97e091de141b13add5d77e9f855f245214a1446616fef6d8b5259c0f5a1ae8",
          "sha256": "0147a767bf3490d1a1a28529aaa163d94bb60abc20ffe17f19d3b321774601f1",
          "sha1": "13570d13fce760c991f509bc57d227706db160e7",
          "md5": "7a880b43c88be2d077eded119c1859c3"
        }
      ]
    },
    {
      "name": "jsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jslegacy-0.1.jar",
          "url": "kococo-release-js-0.1.jar",
          "size": 2678,
          "sha512": "ba0dfe1c6a197f46725769190a801fb968ca08d4508dadc1f7c5c3980cfae3789d97e091de141b13add5d77e9f855f245214a1446616fef6d8b5259c0f5a1ae8",
          "sha256": "0147a767bf3490d1a1a28529aaa163d94bb60abc20ffe17f19d3b321774601f1",
          "sha1": "13570d13fce760c991f509bc57d227706db160e7",
          "md5": "7a880b43c88be2d077eded119c1859c3"
        }
      ]
    },
    {
      "name": "jsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jsir-0.1.klib",
          "url": "kococo-release-js-0.1.klib",
          "size": 2821,
          "sha512": "bf7175d5aa49115bf111cb1667bec97e46a986a5c01cfff7be67c0033844494d5ed20911782eab100a7373968354c948729e887cb0438d909c09f914e4c9879e",
          "sha256": "a6633743439500663345b6b206d2b227aef058464bab77bdd2f0beb6c168b39f",
          "sha1": "c56b08198b13c375ee17359ab1dcefd6f80c0edb",
          "md5": "9467a6ba2f84e666dc1452ccb6798966"
        }
      ]
    },
    {
      "name": "jsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jsir-0.1.klib",
          "url": "kococo-release-js-0.1.klib",
          "size": 2821,
          "sha512": "bf7175d5aa49115bf111cb1667bec97e46a986a5c01cfff7be67c0033844494d5ed20911782eab100a7373968354c948729e887cb0438d909c09f914e4c9879e",
          "sha256": "a6633743439500663345b6b206d2b227aef058464bab77bdd2f0beb6c168b39f",
          "sha1": "c56b08198b13c375ee17359ab1dcefd6f80c0edb",
          "md5": "9467a6ba2f84e666dc1452ccb6798966"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-release-metadata/0.1/kococo-release-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-release-metadata/0.1/kococo-release-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-metadata",
        "version": "0.1"
      }
    }
  ]
}
