{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "55tdhkeanvev3n4g5laj3fbcty"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.0-all.jar",
          "url": "kohomology-0.0-all.jar",
          "size": 25081,
          "sha512": "0024fcde5991192f30c2c249f4b19350d575c7a4707e14f6edaa1c855343ac436117f6b5bc3d30102f2368ad02d20e1cac7b65af5506f36eaa4b2e5ffbec895c",
          "sha256": "73ec008038954c8f7c613032b20cf71f951d581ce4ddad5cd38ea9a8fa32f9f5",
          "sha1": "c96f78eb4446488b38c32ec8599f79df51294da1",
          "md5": "27ad90c40764a63f40a533e506a003cd"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.0.jar",
          "url": "kohomology-0.0.jar",
          "size": 60879,
          "sha512": "32c122ad2c98d6ec74518a388a0b20bc5d11a37d2bd731e8344a0387b7953391b62db2dbe442abf4ec0ffe844f78556c80b32806bc0302e9e6a91d696bc63360",
          "sha256": "d907d207103bc8a538d2eb231952b71dc63f09cdf5db348f017e6ca4a33d3291",
          "sha1": "47c3675ba943f535b502a0704a43df7263154226",
          "md5": "3c4782c00d6fe0b59582a56715b43eca"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.0/kohomology-js-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.0/kohomology-js-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.0/kohomology-js-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.0/kohomology-js-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.0/kohomology-jvm-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.0/kohomology-jvm-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.0"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.0/kohomology-native-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.0"
      }
    }
  ]
}
