{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-release-native/0.1/kococo-release-native-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-release-native",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "y5wcifjiunac3hakjkowrfxxna"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-metadata-0.1-all.jar",
          "url": "kococo-release-metadata-0.1-all.jar",
          "size": 3716,
          "sha512": "91a6d0a7d5a85abe6d788594b551865f73d2e2e81a7071bd8a83bfd23293cd0d95b10d9f8cfad687d43d5659c60e99bfff02cfe502c4398e18c060309fa5ba8a",
          "sha256": "111375e93f7d0a2091786866afbb35d78dd2c20c251ce65fe08f4b33acb96366",
          "sha1": "7db2217da272b28f0dd9b5c8505eb676d3e045e8",
          "md5": "6c1b492348cb93f1e2244d88b0c7f89d"
        }
      ]
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-metadata-0.1.jar",
          "url": "kococo-release-metadata-0.1.jar",
          "size": 1206,
          "sha512": "197c841e3ae9d99625a13a937b4ec8c9f9e986096fe1c96cbb8d2425f0f9d8443d37d567e2e6a9a7bf151863ddbb5e567de54d4f00cdb872eedc9ebeb38c395f",
          "sha256": "d3a5b807a169afa8062323465fe04816810b2bb5f8ed2cb9414f1b70f065541b",
          "sha1": "c12a7246cc86a8164c9577b476b8d3a5ddc09e4e",
          "md5": "437e8fa816237f5fe305a92a5246a304"
        }
      ]
    }
  ]
}
