{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.11/kohomology-0.11.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.11.klib",
          "size": 861240,
          "sha512": "ce3002ef17996a5a8a4dd1cd9cd80d879d5206a576dab3c32ff3808cbb4a40700e28b4e5341bd2c39b12c35935796582e3ce79ddb79351ee85160cfaf7eb1bd4",
          "sha256": "4c949c47109898c5d1470ba9daef72aebec6be4cc7c625728a5e4bfb8c21528e",
          "sha1": "3e64e7bf3c8dcb12196125d0caea03be11f8de10",
          "md5": "fe76a2c0679603366b9324211a5b3ceb"
        }
      ]
    }
  ]
}
