{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug/0.1/kococo-debug-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "oihpmjuen5d6rlqsaveqwct6su"
    }
  },
  "variants": [
    {
      "name": "native-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug.klib",
          "url": "kococo-debug-native-0.1.klib",
          "size": 5290,
          "sha512": "a182f3e64561db6a8de9106d1b1f0aec1587e51367efeea1c79afe77c77b2ddad7d65f1a4dadb1dc4de5026aa927a93da048d111e6fcd309077f59ff4010084c",
          "sha256": "b31faed371f4a13fe40e407b1cda2a6f91bc765b7ea0264c80667f376ca4d981",
          "sha1": "2dfecaf50e573b6c0e9496bceaef0e9d06c65406",
          "md5": "97a21da217d395eec71a560c9a888bbc"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    }
  ]
}
