{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.4/kohomology-0.4.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "675ax42srra6rdnm7t5hswvrpq"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.4.klib",
          "size": 371283,
          "sha512": "387f76d7412f7bb4f315d9fd2fd28556e8e1d479ffc714969f124bcaafabc6abbd14bff05c9fd43098c86dee02ee868b8295abca2f193f16c484d2adc50bab04",
          "sha256": "be0061fef93d25f66352ec6ca4ee479e5694e68ff516d41982593a2aac42b83c",
          "sha1": "e10882e5f95389d58c62b43b8ad2d73085e8d076",
          "md5": "68899f51cb45495b83fff4c359fe151e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.4/kohomology-0.4.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.4"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.4/kohomology-0.4.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.4"
      }
    }
  ]
}
