{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.3/kohomology-0.3.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "a45huneyb5ae3ocafx44fh5a5y"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.3.klib",
          "size": 330462,
          "sha512": "4d7c4f942e3303d1402c9fdfcdb1170104cbc5b28f9f20ac1077e06c2e73a5ded4e8b470e46dc473bee892ce69ecfa2a788e3310219d0de27a1b461f1c5b9f09",
          "sha256": "df6858c67f47347e7fde7f247a47a5f48b008287bad059e30b85b1ce01c35bba",
          "sha1": "763e0033c61ed278c4d8e71128db1ce509a7bc23",
          "md5": "9d5726f966691b852131524d6b7652fc"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.3/kohomology-0.3.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.3"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.3/kohomology-0.3.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.3"
      }
    }
  ]
}
