{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.5/kohomology-0.5.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "arwh7p7evnexzdx4ml27faepfy"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.5.klib",
          "size": 527748,
          "sha512": "d2b59ce086ee69695ff3c49ba6d073ddb06b09ff02bc6f1d94896e9a7bbcd197aa2d3e3b5e6a5edaf585e2b9b8d64e17403aaefd849a730573ec4075b76ae30c",
          "sha256": "07ea98512f5ee8e6e84b31792e35b60dfce89724a989510f7ad460f6ced48a6f",
          "sha1": "b1e922b62d9a805835f5693bc927d3c9e70944b7",
          "md5": "4eaf94781690f8ebdf4f8c3a2e9cd625"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.5/kohomology-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.5"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.5/kohomology-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.5"
      }
    }
  ]
}
