{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parautil-parallel/0.2/parautil-parallel-0.2.module",
    "group": "com.github.shwaka.parautil",
    "module": "parautil-parallel",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "cy7c3tt6jnfe7fpp7yhqriuzq4"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-parallel.klib",
          "url": "parautil-parallel-native-0.2.klib",
          "size": 6622,
          "sha512": "f5a37fb4c448f98989b799740a8f3d2b1f51cba0bfe79a068bca53bf0c2ec0e593df965d1c88e3c77dcd947e7480f4b0f75c4b84ccb4f24993fe21d9a3cdf32c",
          "sha256": "1abf57b89a05716e065d0a32f1c41d66248afa270561f4549d50e672b7bd2dee",
          "sha1": "5a84aa170d08d213db9aefe5ac506fabae5bb4cb",
          "md5": "e28a83d69bc09b59839d3f6f358ed8b1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-parallel/0.2/parautil-parallel-0.2.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel",
        "version": "0.2"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-parallel/0.2/parautil-parallel-0.2.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel",
        "version": "0.2"
      }
    }
  ]
}
