{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.12/kohomology-0.12.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.12.klib",
          "size": 1043842,
          "sha512": "193e33ae035a9c00fec91102a4459f6bb73b63f69560b1e6507fa20b42b98fcff7523491da71c0188816853f86ee7580a2ac6ffa3bef8d434602a7729d086711",
          "sha256": "2b6fa466235f29e3ceeccfefc486fa567b2c95b7df8f0f6f9be0e8c236f42fc6",
          "sha1": "9fdb369c0542a4e174c0563433639df47afb10ea",
          "md5": "c42e93ba5fbdbafa7018ccd55d9c338b"
        }
      ]
    }
  ]
}
