{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.9/kohomology-0.9.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.9.klib",
          "size": 784999,
          "sha512": "606e3a1ce102cb1868ad135026a5c2a2dc9156bb0e1bfbafadfd6a32f3cf34048f3b004baf3efe4e156c418e0801f8dd4070af1bc8e056dfacb341cc9b5c6645",
          "sha256": "20b3981c7e3394847ef3e948c759e4b93d99c4be5b833b0e6c69a070c922ff55",
          "sha1": "b2b41ed30cf5a6b4e8675cbee7745084b942803e",
          "md5": "82ce14d949f352e4a0bd31c4623dea10"
        }
      ]
    }
  ]
}
