{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "z5hav2elabhclfwrfbkestzmy4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.2-all.jar",
          "url": "kohomology-0.2-all.jar",
          "size": 27868,
          "sha512": "d9bbf1814b421f392be7c49f2308c9cab8da734e0c7e0f4a0e865d89dc3506080af94f8e7a90b3495f21eeda46332b37c99b370c4e46917c73b7f7d6f73ef5a6",
          "sha256": "d00e769cc95a9327bba6493eee1bde7e99ab0216604741d6c48f8cf9c658a870",
          "sha1": "ac4683a6f0f403847362f75bce944a8ff5084355",
          "md5": "8a2cdd9947f80848d97d9d113fd364e3"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.2.jar",
          "url": "kohomology-0.2.jar",
          "size": 69176,
          "sha512": "2a376b6da7f770df971615d529460ab47d5e35e3fd746ec8a52f9484e56626777132af7dea2f6d1e8ff201bf74dc319b7197b47b63375284d4e9c3bf4e8b7f4b",
          "sha256": "1d759b74e2357554d99c7e7d832f32c76f8c15142e91c724f772c678bd645e69",
          "sha1": "e6c6fc6ed4ecc8c4fd7cb4538c24900aa15ccf8f",
          "md5": "8ea51b737fd607ae3690a5f43066a836"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.2/kohomology-js-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.2/kohomology-js-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.2/kohomology-js-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.2/kohomology-js-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.2/kohomology-jvm-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.2/kohomology-jvm-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.2/kohomology-native-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.2"
      }
    }
  ]
}
