{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
    "group": "com.github.shwaka.parautil",
    "module": "parautil-nonparallel",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "txyxacvryjdqvi5q4ktcc4ebuq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "parautil-nonparallel-jvm-0.1.jar",
          "url": "parautil-nonparallel-jvm-0.1.jar",
          "size": 2794,
          "sha512": "74c9b71bff044840ce404b603747728884d4e8e8d1b94f097c8ec43c4dbd5a6103e42561baa8cacd4fa6ec57952e65102757ada71d3e696791c06e6fa519e7ff",
          "sha256": "fd0395630d0ad19145af915e1232ba59e2cb72850601a336883defa2ff639fa5",
          "sha1": "4dbdf57fd8eb50cb328968f35d05c42edb9857ea",
          "md5": "8bf2009fd9f689c52a237928f5fa41d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-nonparallel-jvm-0.1.jar",
          "url": "parautil-nonparallel-jvm-0.1.jar",
          "size": 2794,
          "sha512": "74c9b71bff044840ce404b603747728884d4e8e8d1b94f097c8ec43c4dbd5a6103e42561baa8cacd4fa6ec57952e65102757ada71d3e696791c06e6fa519e7ff",
          "sha256": "fd0395630d0ad19145af915e1232ba59e2cb72850601a336883defa2ff639fa5",
          "sha1": "4dbdf57fd8eb50cb328968f35d05c42edb9857ea",
          "md5": "8bf2009fd9f689c52a237928f5fa41d1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-nonparallel",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-nonparallel",
        "version": "0.1"
      }
    }
  ]
}
