{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o2x7bm3lqzhkngoogh6vocrekm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.1-all.jar",
          "url": "kohomology-0.1-all.jar",
          "size": 26623,
          "sha512": "b58876329a31a51ca97a9e415d96c82c674d590830f7473171c3e86b0e7a93242fbc1315253c548776eeb513b828a044344faad97414299f6a4721880f252c93",
          "sha256": "942ff4383c8836c142d43dcf1f648289d288b5a437ddbd68bb31fdfce41af7bb",
          "sha1": "d9380abe865cbe79d6d8cdb54ba8862cde978234",
          "md5": "3664ed48e603fef3c1c53c6743b0ffdd"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.1.jar",
          "url": "kohomology-0.1.jar",
          "size": 64312,
          "sha512": "73eb0ebacb4db57c9d054dd9384be94d0a71bb66be682e08d535e476b247a6392276a7b6f33377a70b869c157aa4b84979ff57735a6385916710731c0726133b",
          "sha256": "76b2d3da862c2c39259a4c67f8d3bc1a627d12f8232f7dc725100443a13720c0",
          "sha1": "a4fe04eae25be8d6b3ea8bcf1759c43ba5b0582b",
          "md5": "87d69f193309fba631ba1f4d6dda745a"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.1/kohomology-js-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.1/kohomology-js-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.1/kohomology-js-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.1/kohomology-js-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.1/kohomology-jvm-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.1/kohomology-jvm-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.1/kohomology-native-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.1"
      }
    }
  ]
}
