{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.5/kohomology-0.5.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "arwh7p7evnexzdx4ml27faepfy"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.5.jar",
          "url": "kohomology-js-0.5.jar",
          "size": 269342,
          "sha512": "e0ee41eab8905a56d17b9d2a19f3446da398aebfb2ff9b9fa4b8d6b913f1b60c8ee4dd9b29da81cd552cbc9b7dbf5ec8bb27c9a02dab9eb43583d44f028effa0",
          "sha256": "3d8f54aeed218838d7df5c4e5e1d808352c9d783db7c027697779e8b531281b4",
          "sha1": "8014091ba337bd07f26ca65e0fe219236b615498",
          "md5": "25965932afdf54ce6156aee6c4c0e259"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.5.jar",
          "url": "kohomology-js-0.5.jar",
          "size": 269342,
          "sha512": "e0ee41eab8905a56d17b9d2a19f3446da398aebfb2ff9b9fa4b8d6b913f1b60c8ee4dd9b29da81cd552cbc9b7dbf5ec8bb27c9a02dab9eb43583d44f028effa0",
          "sha256": "3d8f54aeed218838d7df5c4e5e1d808352c9d783db7c027697779e8b531281b4",
          "sha1": "8014091ba337bd07f26ca65e0fe219236b615498",
          "md5": "25965932afdf54ce6156aee6c4c0e259"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.5.klib",
          "url": "kohomology-js-0.5.klib",
          "size": 561495,
          "sha512": "be9f5e49baf979963b85035d26420ffbde2b52b08ef0812b05c7cd4b672fb7d276700bed5aeba24f2d07a6432d22766533afc920045c7ad4366af0174caac3c5",
          "sha256": "8924b2fb90122460b464b26b04f85b431337009276f670587147618f1c2e0561",
          "sha1": "fa6b807e0f00256882f64a33cd5e5329a85175e8",
          "md5": "2f375dcc2191254956e6b2751ad93e60"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.5.klib",
          "url": "kohomology-js-0.5.klib",
          "size": 561495,
          "sha512": "be9f5e49baf979963b85035d26420ffbde2b52b08ef0812b05c7cd4b672fb7d276700bed5aeba24f2d07a6432d22766533afc920045c7ad4366af0174caac3c5",
          "sha256": "8924b2fb90122460b464b26b04f85b431337009276f670587147618f1c2e0561",
          "sha1": "fa6b807e0f00256882f64a33cd5e5329a85175e8",
          "md5": "2f375dcc2191254956e6b2751ad93e60"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.5/kohomology-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.5"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.5/kohomology-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.5"
      }
    }
  ]
}
