{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "arwh7p7evnexzdx4ml27faepfy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.5-all.jar",
          "url": "kohomology-0.5-all.jar",
          "size": 47545,
          "sha512": "1267f88d3aec211e65b1fb65b95df31ac7ed9d8c8c44bc0c353c034a660c2421c0ddabdda35cb2d21f84c2a8829c8435e8e18d7ce7882598b6dc405a12d74d16",
          "sha256": "61ace920cc4899aeb5a9610c1d1f2415b4b8cfdfd7baa472409788f1e638b4b6",
          "sha1": "4433464ed97b88118c83f25144f89fb4d35902aa",
          "md5": "a32720cabc08f8b8754cb9c855871485"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.5.jar",
          "url": "kohomology-0.5.jar",
          "size": 133932,
          "sha512": "7fddff65506e953c796c5d891fb7169db2794f42ae46fc00750824a980ce4d44ad7af25df95f5af650d02c0db967e34470bd97ae5b92de4f566e306f977aa813",
          "sha256": "d54f30542c78886af1b7695e218500e4d2bfd6bfa296a4fbc054dc0bc86e50c0",
          "sha1": "a2041b2d00b2bff1c783dcdc4381427866b2221b",
          "md5": "c5c66662f18be4c059ca5de3bb5c5ef2"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.5/kohomology-js-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.5"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.5/kohomology-js-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.5"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.5/kohomology-js-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.5"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.5/kohomology-js-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.5/kohomology-jvm-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.5/kohomology-jvm-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.5"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.5/kohomology-native-0.5.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.5"
      }
    }
  ]
}
