{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug/0.1/kococo-debug-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "oihpmjuen5d6rlqsaveqwct6su"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jvm-0.1.jar",
          "url": "kococo-debug-jvm-0.1.jar",
          "size": 1649,
          "sha512": "c4af4799b2af9a21b03b8dae0f0408c0e96be001bb68365adc4d8d6bd339950d9da7652b77a91c18ca470e6fb68084b91e93162efa24e786b5335e695c0406a1",
          "sha256": "f0558352404df556d6fa3a61912ffb265aa66abef91d0993f96ae67a56414ebb",
          "sha1": "de22e8d82a92b4ddcad54007cbdd185e78855f77",
          "md5": "a12b6fb16cbf59d77a8cb50c45ac6493"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jvm-0.1.jar",
          "url": "kococo-debug-jvm-0.1.jar",
          "size": 1649,
          "sha512": "c4af4799b2af9a21b03b8dae0f0408c0e96be001bb68365adc4d8d6bd339950d9da7652b77a91c18ca470e6fb68084b91e93162efa24e786b5335e695c0406a1",
          "sha256": "f0558352404df556d6fa3a61912ffb265aa66abef91d0993f96ae67a56414ebb",
          "sha1": "de22e8d82a92b4ddcad54007cbdd185e78855f77",
          "md5": "a12b6fb16cbf59d77a8cb50c45ac6493"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    }
  ]
}
