{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.4/kohomology-0.4.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "675ax42srra6rdnm7t5hswvrpq"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.4.jar",
          "url": "kohomology-js-0.4.jar",
          "size": 212021,
          "sha512": "833b4d6187a9c3042f824638fbe20e0533eb91ebbd88b084ad98c51aba01f15a8e3b1c87a74871c1764c661b3d9d72173c7306bbaf701c100b7581efac32a613",
          "sha256": "6fbec0f326e785680b6bf3fbd71c1c1cca5c96755395dab4671da49ac9039911",
          "sha1": "0fc3f10f0e4f73e65099080cfd16e861cc1876b7",
          "md5": "a0c8e7adb02b1e0d5db90a22103ff565"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.4.jar",
          "url": "kohomology-js-0.4.jar",
          "size": 212021,
          "sha512": "833b4d6187a9c3042f824638fbe20e0533eb91ebbd88b084ad98c51aba01f15a8e3b1c87a74871c1764c661b3d9d72173c7306bbaf701c100b7581efac32a613",
          "sha256": "6fbec0f326e785680b6bf3fbd71c1c1cca5c96755395dab4671da49ac9039911",
          "sha1": "0fc3f10f0e4f73e65099080cfd16e861cc1876b7",
          "md5": "a0c8e7adb02b1e0d5db90a22103ff565"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.4.klib",
          "url": "kohomology-js-0.4.klib",
          "size": 391149,
          "sha512": "4d90e544e02e9905704d5dc98e6d600b7fed6c4bb7cfe13081555f95a80c18cd83ddaa90d56ef919b074f528c58d2f8738fb6713cd9d2676da1b65de905d05be",
          "sha256": "be1e2e967c48210d6f39890e1ac64bdf09f5ad00a27b70358c18db7e442fafc4",
          "sha1": "b7a12793c7e85c9c9dfc51eb264056a063e9ae21",
          "md5": "82bfb124c4e081b90b7e04d7d1eeab5f"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.4.klib",
          "url": "kohomology-js-0.4.klib",
          "size": 391149,
          "sha512": "4d90e544e02e9905704d5dc98e6d600b7fed6c4bb7cfe13081555f95a80c18cd83ddaa90d56ef919b074f528c58d2f8738fb6713cd9d2676da1b65de905d05be",
          "sha256": "be1e2e967c48210d6f39890e1ac64bdf09f5ad00a27b70358c18db7e442fafc4",
          "sha1": "b7a12793c7e85c9c9dfc51eb264056a063e9ae21",
          "md5": "82bfb124c4e081b90b7e04d7d1eeab5f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.4/kohomology-0.4.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.4"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.4/kohomology-0.4.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.4"
      }
    }
  ]
}
