{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kococo",
    "module": "kococo-release",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-metadata-0.2.jar",
          "url": "kococo-release-0.2.jar",
          "size": 3702,
          "sha512": "3445f118c6519e8f6279e352b7b24e7f145a3bc60cd2dd749b7256675ec4f42b9a65b4c7028b8e2ed3724eed6e59943e78a45fa8395889e1630e01692d274b69",
          "sha256": "2eb93c98b36ad988ebebf1a1896c83e46593adc9b54c9691cc63a4f41a65e247",
          "sha1": "0916d45256540e25a0b6683e81021b410f42d9df",
          "md5": "981b7ff4bd5e5e4bc94ac1ad66abe809"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kococo-release-kotlin-0.2-sources.jar",
          "url": "kococo-release-0.2-sources.jar",
          "size": 578,
          "sha512": "039612bd496dc68989a67b35b7af49763bd0c4c6daa2650ded030e4a8381816af9c7d7256ea88ef33667e33852b36b48a0089de2d5a5aa975a657ed74844e7ff",
          "sha256": "53aec6c24d244663dadb7c654b9adc288df99c400e159641253601a85c403daa",
          "sha1": "0292369f0406d61b35b1254e6e83d4ba9de2abfb",
          "md5": "1de412991dda44f20f2c284628b601f2"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-release-js/0.2/kococo-release-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-release-js/0.2/kococo-release-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-release-js/0.2/kococo-release-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-js",
        "version": "0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-release-jvm/0.2/kococo-release-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-release-jvm/0.2/kococo-release-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-release-jvm/0.2/kococo-release-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kococo-release-native/0.2/kococo-release-native-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-native",
        "version": "0.2"
      }
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kococo-release-native/0.2/kococo-release-native-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-native",
        "version": "0.2"
      }
    }
  ]
}
