{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.8/kohomology-0.8.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.8.jar",
          "url": "kohomology-jvm-0.8.jar",
          "size": 945168,
          "sha512": "947b3f39dfcf5fe1e42ba7684fe81fb9e3ef8b254719d6d92d9d4790c8342434e10d8810d8020debd38beccfcbaf3ae6e54436bd001f6af75538683946e53924",
          "sha256": "8deb2210012bd155ac1c8b2da5a111e05f0facdfda8dd64c3dc7acd6fedc7473",
          "sha1": "9b6cb0d088040046e2c6a8b08e830931701cfc2c",
          "md5": "7b4da174cdd3364d01d6b55048a54037"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.8.jar",
          "url": "kohomology-jvm-0.8.jar",
          "size": 945168,
          "sha512": "947b3f39dfcf5fe1e42ba7684fe81fb9e3ef8b254719d6d92d9d4790c8342434e10d8810d8020debd38beccfcbaf3ae6e54436bd001f6af75538683946e53924",
          "sha256": "8deb2210012bd155ac1c8b2da5a111e05f0facdfda8dd64c3dc7acd6fedc7473",
          "sha1": "9b6cb0d088040046e2c6a8b08e830931701cfc2c",
          "md5": "7b4da174cdd3364d01d6b55048a54037"
        }
      ]
    }
  ]
}
