{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.2/kohomology-0.2.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "z5hav2elabhclfwrfbkestzmy4"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.2.klib",
          "size": 292311,
          "sha512": "c4b6d83f931ad50bfbfc707e0104c9b27738aa7a06681f08e0ab25e27fba71c7f5eae8fbd2e4140faf9ff73eee6a8c23fc1bfbf5c1d8d2c4469a74b159710e2c",
          "sha256": "0317892cba85eb31143af0212d99e41304fba8755e0984335abd4f204286746e",
          "sha1": "f4e87fece2edb37d209b3fdc5f91c755ac06d0bb",
          "md5": "6b710776cf683b64a44548bd9f43c8d7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.2/kohomology-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.2"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.2/kohomology-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.2"
      }
    }
  ]
}
