{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.parautil",
    "module": "parautil-parallel",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "vkxs7dku7vbefgwnl3o2noj5t4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "parautil-parallel-metadata-0.1-all.jar",
          "url": "parautil-parallel-0.1-all.jar",
          "size": 4368,
          "sha512": "9b80c1ced9b134021dcf58d08b0025aca008166da810a7500abd9f339920889ba8de471a3ad5077c740caa076fad442d5479c5a0f2900146f94458bf0bb64b82",
          "sha256": "7dab57964628dcb6436ab933149e5cd3fe6c568015eec12fd7cedf4dd8d8185c",
          "sha1": "680ada38df416836a7622bb98f521fb2243ed1fa",
          "md5": "018dd599eac15db5dca6a8de846abd23"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "parautil-parallel-0.1.jar",
          "url": "parautil-parallel-0.1.jar",
          "size": 1535,
          "sha512": "70845794ddf2144048906085ac85d26b36d5ee6b5292153f7cb5884b81a8ec1f048070441f26b97d1f4d124de34ba3b2bec09283f16f17ac82693f5389fc2f57",
          "sha256": "a71d7f06f81d7a07559d41f1f4d2d7f335945d0dfad3275b26c9b04e117f4817",
          "sha1": "55d8964e49f941bb424a7e94bc0a049351f8d11c",
          "md5": "7bff2785d1b3dc94251bef50b22a4ad3"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parautil-parallel-js/0.1/parautil-parallel-js-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parautil-parallel-js/0.1/parautil-parallel-js-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parautil-parallel-js/0.1/parautil-parallel-js-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parautil-parallel-js/0.1/parautil-parallel-js-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-js",
        "version": "0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../parautil-parallel-jvm/0.1/parautil-parallel-jvm-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../parautil-parallel-jvm/0.1/parautil-parallel-jvm-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parautil-parallel-native/0.1/parautil-parallel-native-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel-native",
        "version": "0.1"
      }
    }
  ]
}
