{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotex/0.1/kotex-0.1.module",
    "group": "me.shun",
    "module": "kotex",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "kotex.klib",
          "url": "kotex-native-0.1.klib",
          "size": 18292,
          "sha512": "958fec525c2731b5f6143d7d6beb20e9601b4f61e2df61f847c46e187c77b68666279271a45ae0de80afe7826e2f891380cec6165d98bef61f68d7840361d134",
          "sha256": "41e35a35fd092da41e20150e79fa471f52c8ebfc7485e7f7b1fe82c48fb7eea3",
          "sha1": "8bf62e900683745af1f6b7e35c0b57146f923c6a",
          "md5": "eb1dbc47b0b1c4c5109ead3b6ba1d572"
        }
      ]
    }
  ]
}
