{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.6/kohomology-0.6.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "r7wgcldtr5gf5bo7ttwdbubywq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.6.jar",
          "url": "kohomology-jvm-0.6.jar",
          "size": 868824,
          "sha512": "92c43912fe347ae48a54a0725ebabfc4bd0fb4df98830738c0d712a995ecaa02ab9c10c5abf46de499181b0a62f197925ef6749794335341307001e0d895b014",
          "sha256": "385cbcfd1ecdac8b51cf3924e1093e408e9fe724ce21797d4f4b027c6de77daa",
          "sha1": "30ea36fcfa6513ae5f1aea26bb7855c49304583a",
          "md5": "6788795c43ff9536f586c71b501bb63e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.6.jar",
          "url": "kohomology-jvm-0.6.jar",
          "size": 868824,
          "sha512": "92c43912fe347ae48a54a0725ebabfc4bd0fb4df98830738c0d712a995ecaa02ab9c10c5abf46de499181b0a62f197925ef6749794335341307001e0d895b014",
          "sha256": "385cbcfd1ecdac8b51cf3924e1093e408e9fe724ce21797d4f4b027c6de77daa",
          "sha1": "30ea36fcfa6513ae5f1aea26bb7855c49304583a",
          "md5": "6788795c43ff9536f586c71b501bb63e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.6/kohomology-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.6"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.6/kohomology-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.6"
      }
    }
  ]
}
