{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.0/kohomology-0.0.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "55tdhkeanvev3n4g5laj3fbcty"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.0.klib",
          "size": 228164,
          "sha512": "e294ac6261ca70135352c30f35023df49b082bc2bd0e5e0c03cfd462562cb51b03909a314a440bbdd3f9452f993388a4c5a3122e84bfadfc7f17aa5c145f3a63",
          "sha256": "eca25e83f5824cb52c9e769dd6cc200459337c8b0e64e48cc3e41f8452e2af0d",
          "sha1": "3b09affc222962f0ea4f14b01037ad1137ab98c8",
          "md5": "9271ae4035bc52a301de5c31fe80b25d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.0/kohomology-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.0"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.0/kohomology-0.0.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.0"
      }
    }
  ]
}
