{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.10/kohomology-0.10.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.10.jar",
          "url": "kohomology-jvm-0.10.jar",
          "size": 1380039,
          "sha512": "ab4122ee9ecdc5f3e637763ebd0a4de52703529604b2be119da8a49b4b80088ca2a485b237c58ffacdc6f11b661ec17ea5a8aef09794dfcf90d91a6a81c6fec9",
          "sha256": "be9e4c8c6d5390a48919f212e9ef6f18eda1f888469324af3aa7058539e2a7a8",
          "sha1": "c2c2365515bf8fe89c23bf2af5ac3dc3eef7ea3a",
          "md5": "6d180dad634287a804f8fd6a2be978fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.10.jar",
          "url": "kohomology-jvm-0.10.jar",
          "size": 1380039,
          "sha512": "ab4122ee9ecdc5f3e637763ebd0a4de52703529604b2be119da8a49b4b80088ca2a485b237c58ffacdc6f11b661ec17ea5a8aef09794dfcf90d91a6a81c6fec9",
          "sha256": "be9e4c8c6d5390a48919f212e9ef6f18eda1f888469324af3aa7058539e2a7a8",
          "sha1": "c2c2365515bf8fe89c23bf2af5ac3dc3eef7ea3a",
          "md5": "6d180dad634287a804f8fd6a2be978fb"
        }
      ]
    }
  ]
}
