{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adarshr",
    "module": "gradle-test-logger-plugin",
    "version": "3.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "rdh2dnrzlfh7nmv56as5lradyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-test-logger-plugin-3.0.1-SNAPSHOT.jar",
          "url": "gradle-test-logger-plugin-3.0.1-SNAPSHOT.jar",
          "size": 143122,
          "sha512": "aa1435fb429430eef089131d932b335156c66b139fe46d25fda9dd40e3b6b63aeffd2ccd7318f4ed98f681a96c44f4d61717b1218e05361a5c7fc9c6c90bd26b",
          "sha256": "96aed4339f24a3da7bd654f0a6f06488131e2d3469e61c0050feaec38e01ea19",
          "sha1": "b010dfcdfff13a680d8af6aac0eb5333d481bcbc",
          "md5": "4d9a866cb2f36984e0ca029b8fc68dfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-test-logger-plugin-3.0.1-SNAPSHOT.jar",
          "url": "gradle-test-logger-plugin-3.0.1-SNAPSHOT.jar",
          "size": 143122,
          "sha512": "aa1435fb429430eef089131d932b335156c66b139fe46d25fda9dd40e3b6b63aeffd2ccd7318f4ed98f681a96c44f4d61717b1218e05361a5c7fc9c6c90bd26b",
          "sha256": "96aed4339f24a3da7bd654f0a6f06488131e2d3469e61c0050feaec38e01ea19",
          "sha1": "b010dfcdfff13a680d8af6aac0eb5333d481bcbc",
          "md5": "4d9a866cb2f36984e0ca029b8fc68dfb"
        }
      ]
    }
  ]
}
