{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-metadata-0.2.jar",
          "url": "kococo-debug-0.2.jar",
          "size": 3700,
          "sha512": "eb2d6d6b5c084ac987dbe7d3222f215041b2433c0a77cf0157cae115694295587535aab03be342b70aea5f9cdedbde9fdb43047cd8d0a543e7630ab8865aee12",
          "sha256": "451f024905865ab9e0e6455d6816f15e48a629b99fb182cf8b4af7389c583d65",
          "sha1": "d7acd9e032e546e072757b303c885df3d866827d",
          "md5": "3b2cec0fb6573c97c7d7d2777cee380f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kococo-debug-kotlin-0.2-sources.jar",
          "url": "kococo-debug-0.2-sources.jar",
          "size": 556,
          "sha512": "5619406db31fe030e4b48022e09ad8dd9e211012ecf689ce4e9474fa57acc4d7f1c9dc7ff6a4c61ab0dea661be6fed484d0c9cb11eafaae2e4dae62556427048",
          "sha256": "c3d362ff76f34b2a3cbfcad9acf8ab1af9aebc37aa2d6f090242e7045f3d83b3",
          "sha1": "65a46aa47f64868c9b9898e3bbfca3c018844238",
          "md5": "6a2604c9ddbd1c7a6dfa177a129d3adc"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-debug-js/0.2/kococo-debug-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-debug-js/0.2/kococo-debug-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kococo-debug-js/0.2/kococo-debug-js-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-js",
        "version": "0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-debug-jvm/0.2/kococo-debug-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-debug-jvm/0.2/kococo-debug-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kococo-debug-jvm/0.2/kococo-debug-jvm-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kococo-debug-native/0.2/kococo-debug-native-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-native",
        "version": "0.2"
      }
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kococo-debug-native/0.2/kococo-debug-native-0.2.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-native",
        "version": "0.2"
      }
    }
  ]
}
