{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
    "group": "com.github.shwaka.parautil",
    "module": "parautil-nonparallel",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "txyxacvryjdqvi5q4ktcc4ebuq"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-nonparallel-jslegacy-0.1.jar",
          "url": "parautil-nonparallel-js-0.1.jar",
          "size": 17287,
          "sha512": "a202f5f98f1ad287f252260c46f056c63f610044443b3b8deca7e4e3c56cf98ddfa48a24413f18c2ca0abb436a37f86fd47a2691b9d37a9c426cc38dbab83663",
          "sha256": "5e924a9326ac56b47974bd5c1a2af608d086ac56e66f0a38c2c4ebd1ba2aaeda",
          "sha1": "4e5176c4adf78206de0041c880a83c5a7a65960e",
          "md5": "f93a96a0ab8bf236c568dc282b5fe263"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-nonparallel-jslegacy-0.1.jar",
          "url": "parautil-nonparallel-js-0.1.jar",
          "size": 17287,
          "sha512": "a202f5f98f1ad287f252260c46f056c63f610044443b3b8deca7e4e3c56cf98ddfa48a24413f18c2ca0abb436a37f86fd47a2691b9d37a9c426cc38dbab83663",
          "sha256": "5e924a9326ac56b47974bd5c1a2af608d086ac56e66f0a38c2c4ebd1ba2aaeda",
          "sha1": "4e5176c4adf78206de0041c880a83c5a7a65960e",
          "md5": "f93a96a0ab8bf236c568dc282b5fe263"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-nonparallel-jsir-0.1.klib",
          "url": "parautil-nonparallel-js-0.1.klib",
          "size": 3628,
          "sha512": "8c7aaef50be94c48f692f3face90835d92ccf4b09cf725b245200c0444b650010d6bd2f47494a1021ea6f380dcaaf730ee12e7123dfd0d32b1e5af2afeecd86c",
          "sha256": "a71f7eb64eda6d6123cd1cc20972396f9445c74f78d4d8ddd211680c9f9a1137",
          "sha1": "105751d00c8166bf57ba7fcf9fb599b90b7c65ee",
          "md5": "670cb48568f2411305428912ad7a74ce"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-nonparallel-jsir-0.1.klib",
          "url": "parautil-nonparallel-js-0.1.klib",
          "size": 3628,
          "sha512": "8c7aaef50be94c48f692f3face90835d92ccf4b09cf725b245200c0444b650010d6bd2f47494a1021ea6f380dcaaf730ee12e7123dfd0d32b1e5af2afeecd86c",
          "sha256": "a71f7eb64eda6d6123cd1cc20972396f9445c74f78d4d8ddd211680c9f9a1137",
          "sha1": "105751d00c8166bf57ba7fcf9fb599b90b7c65ee",
          "md5": "670cb48568f2411305428912ad7a74ce"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-nonparallel",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-nonparallel/0.1/parautil-nonparallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-nonparallel",
        "version": "0.1"
      }
    }
  ]
}
