{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-release/0.2/kococo-release-0.2.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-release",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release.klib",
          "url": "kococo-release-native-0.2.klib",
          "size": 5479,
          "sha512": "6576595dfd8db72c6123865ba827305db7b78c3a9b0012391f94d522686cde3659090109e2a0252055931b627c1afb6b203b993c9d1355e9c828ac8241d7c2a3",
          "sha256": "13fda59af18d252fc12663af21b0e8dcfe3c217df34874e641580dc0c84a8ada",
          "sha1": "2e2cc366b7708aad9c9b53829cc5c14d986f828f",
          "md5": "3d6a87aca7bd80bdf038e6e567178da0"
        }
      ]
    },
    {
      "name": "nativeSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kococo-release-native-0.2-sources.jar",
          "url": "kococo-release-native-0.2-sources.jar",
          "size": 578,
          "sha512": "039612bd496dc68989a67b35b7af49763bd0c4c6daa2650ded030e4a8381816af9c7d7256ea88ef33667e33852b36b48a0089de2d5a5aa975a657ed74844e7ff",
          "sha256": "53aec6c24d244663dadb7c654b9adc288df99c400e159641253601a85c403daa",
          "sha1": "0292369f0406d61b35b1254e6e83d4ba9de2abfb",
          "md5": "1de412991dda44f20f2c284628b601f2"
        }
      ]
    }
  ]
}
