{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jxdi6zog7bflbdovf7kt6isiju"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.7-all.jar",
          "url": "kohomology-0.7-all.jar",
          "size": 51115,
          "sha512": "8385c29837cf6733de04bd48b368a4e606cbabdf88b970e3251b2a422124f2d2f81a96cbfa91f42f2422e7543cd9430dbe4ecdd6f6789aab49962d315ea7a209",
          "sha256": "1195b2d3b9d5f78632ed589ee0e4574225348c857105cda53f6be41724845334",
          "sha1": "fd2e4ba2d76f0be940e055c4d5b95daa44c79bc1",
          "md5": "180793a861bc089484f3fca9f97669ec"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.7.jar",
          "url": "kohomology-0.7.jar",
          "size": 139803,
          "sha512": "33d807bffb779b0f0b8b42353ed792a582ebee977fea2c03f7b6929b025a2d385b41ef5ea56de083346c035580fee6677e19beb018389c23771f88b3237b12f4",
          "sha256": "18421c2a020a715234075a6194f57669db3c544907962852c18ef7dd539e7dc8",
          "sha1": "07b5a9e05d94a1369b194bee4e0acfd6765318da",
          "md5": "b46ef1bc481767f756ef07e3e44d2592"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.7/kohomology-js-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.7"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.7/kohomology-js-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.7"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.7/kohomology-js-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.7"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.7/kohomology-js-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.7"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.7/kohomology-jvm-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.7"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.7/kohomology-jvm-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.7"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.7/kohomology-native-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.7"
      }
    }
  ]
}
