{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-release/0.1/kococo-release-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-release",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "y5wcifjiunac3hakjkowrfxxna"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jvm-0.1.jar",
          "url": "kococo-release-jvm-0.1.jar",
          "size": 1617,
          "sha512": "a9c0f185ec4141431ab4b8f26a2130afcc25998bbbcede3d14d7ebe4a5c8485a74498527800feac3643d45ef2a2ce865a17cc520ecae7339d5df8b89cfc4e6bd",
          "sha256": "7b9cf004a266b2fe81d1c9f4d4a3140c644f79018c864c1aeeaf5e602b1b6d28",
          "sha1": "860b7208f8dde9e5e72ee29b5f71608a54edd3e7",
          "md5": "f66cd7e615a232bccba9357327957803"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-release-jvm-0.1.jar",
          "url": "kococo-release-jvm-0.1.jar",
          "size": 1617,
          "sha512": "a9c0f185ec4141431ab4b8f26a2130afcc25998bbbcede3d14d7ebe4a5c8485a74498527800feac3643d45ef2a2ce865a17cc520ecae7339d5df8b89cfc4e6bd",
          "sha256": "7b9cf004a266b2fe81d1c9f4d4a3140c644f79018c864c1aeeaf5e602b1b6d28",
          "sha1": "860b7208f8dde9e5e72ee29b5f71608a54edd3e7",
          "md5": "f66cd7e615a232bccba9357327957803"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-release-metadata/0.1/kococo-release-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-release-metadata/0.1/kococo-release-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-release-metadata",
        "version": "0.1"
      }
    }
  ]
}
