{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.10/kohomology-0.10.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.10.klib",
          "size": 843595,
          "sha512": "57051f4f0eab055a103c2b8bea76d0e0605deacb3e0cf3309b1a6974a1e531ab6b4883a08e72b3396f6af505fdbd2b44128505680eb050b16c2ac2692d08f7cc",
          "sha256": "64d8ab8b86fa32f8ce1921f6f7926dd4fcb33b420e299cd4e4778f57b79cef50",
          "sha1": "2b62cd4ae5d7d1a5357687f330b831ee2fc3ae48",
          "md5": "026a7a4e0d0724e00368a4d9c1f07bdb"
        }
      ]
    }
  ]
}
