{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.1/kohomology-0.1.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o2x7bm3lqzhkngoogh6vocrekm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.1.jar",
          "url": "kohomology-jvm-0.1.jar",
          "size": 332495,
          "sha512": "0aa8618c088ecf5add59f1b31c919c841d4609f6493226c7f6d32aba5263becec83ab12125c9acd647ece9fd95db6f94b8fba54695a6db435d8d67833d077849",
          "sha256": "a22b1467852f8afaff8339f345075abeb91b381a6cb9c00cc6d0ecb6072c8031",
          "sha1": "8a80242ce2c19eb3687009e9449ba7ebccbe07b9",
          "md5": "2bfa5efe3fa202c478902f299f4f3fe0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.1.jar",
          "url": "kohomology-jvm-0.1.jar",
          "size": 332495,
          "sha512": "0aa8618c088ecf5add59f1b31c919c841d4609f6493226c7f6d32aba5263becec83ab12125c9acd647ece9fd95db6f94b8fba54695a6db435d8d67833d077849",
          "sha256": "a22b1467852f8afaff8339f345075abeb91b381a6cb9c00cc6d0ecb6072c8031",
          "sha1": "8a80242ce2c19eb3687009e9449ba7ebccbe07b9",
          "md5": "2bfa5efe3fa202c478902f299f4f3fe0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    }
  ]
}
