{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.7/kohomology-0.7.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jxdi6zog7bflbdovf7kt6isiju"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.7.klib",
          "size": 566687,
          "sha512": "1f56e1c0a358aca554161de415488b35828733e41b512211bd99fda54b776583d524ecf5e8cf832860f8894ea512ac2186a2b00d8be9fe2eefe8f71c1916582b",
          "sha256": "cd467d57eef4cdda87ec2e0c307b0bfbed9a6d8be8f71f7015333058cb09d647",
          "sha1": "43717d33f8564397e6c02e03c5f3f0e64a863c70",
          "md5": "a32077bc9cc9697d5ba9ab8a77d12073"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.7/kohomology-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.7"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.7/kohomology-0.7.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.7"
      }
    }
  ]
}
