{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug-native/0.1/kococo-debug-native-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug-native",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "oihpmjuen5d6rlqsaveqwct6su"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-metadata-0.1-all.jar",
          "url": "kococo-debug-metadata-0.1-all.jar",
          "size": 3714,
          "sha512": "e3ec471c3bb23b9b78df52ce5965d7762078e8145c8310f970e0a994c51397f3632bd7217de2c6bd353601906ecac2acc31ac3c5e2295d18bd0ef70635c17e93",
          "sha256": "d0c09d395e1b03b9667b708e03505630c0e763675cec1182e29e14bef31fbe3e",
          "sha1": "01fd7ac18ff1c0bdf42c23567400af071b85af90",
          "md5": "ef903ca95bd2c6b35ff4a744dd7e337e"
        }
      ]
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-metadata-0.1.jar",
          "url": "kococo-debug-metadata-0.1.jar",
          "size": 1202,
          "sha512": "d3a19d3de9573d01cc2037d182a85aef03fd2a24729da33801a827a701c356dbff770fc422f063fab46cdd12e571aa089b68e72b68a3ffd9071acd62de408817",
          "sha256": "78800652172f424248254146aeef0c440099427ea46f5b7720e81177d5e8851d",
          "sha1": "7475c93e6544033b01cc3104e87cd3966a3d05e2",
          "md5": "95e6119d2ee116025eb8362fec5780da"
        }
      ]
    }
  ]
}
