{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.3/kohomology-0.3.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "a45huneyb5ae3ocafx44fh5a5y"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.3.jar",
          "url": "kohomology-jvm-0.3.jar",
          "size": 472575,
          "sha512": "b6185f51e3d306ddd08da78a24f5a7b1eef1305b852cf728db914610c8d916c80ff1198ec0cbbca5556477cf3a988d740fe457e840555e0bb62f062fdb2cd7f6",
          "sha256": "b0cf2b4cfca1745410ec14f03d915b8b43678234c3d1ba79ec1e54a3bc438413",
          "sha1": "2010d75df8b47302878f8053c707e1ffc7890164",
          "md5": "61956126f2f9fb3722501efa50e0e7cc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.3.jar",
          "url": "kohomology-jvm-0.3.jar",
          "size": 472575,
          "sha512": "b6185f51e3d306ddd08da78a24f5a7b1eef1305b852cf728db914610c8d916c80ff1198ec0cbbca5556477cf3a988d740fe457e840555e0bb62f062fdb2cd7f6",
          "sha256": "b0cf2b4cfca1745410ec14f03d915b8b43678234c3d1ba79ec1e54a3bc438413",
          "sha1": "2010d75df8b47302878f8053c707e1ffc7890164",
          "md5": "61956126f2f9fb3722501efa50e0e7cc"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.3/kohomology-0.3.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.3"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.3/kohomology-0.3.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.3"
      }
    }
  ]
}
