{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.12/kohomology-0.12.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.12.jar",
          "url": "kohomology-jvm-0.12.jar",
          "size": 1719179,
          "sha512": "9b0f37c139d51a2c1783a1dfc6f0d2f3726a9d27256d572761243f0f0cb05c0f0ffcdc921240e0dccb80f0863c7baac6689f4c6bd39cdfe0a1eca3dde337342a",
          "sha256": "33b97973215f2b1a771f3951e838493e73433ad62abb54a3b1f43abae566d0e6",
          "sha1": "b5f0b26f418d0e687f3b48b52c6f2ce6df830a46",
          "md5": "8f66f408f291c894495b38d13d177adb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.12.jar",
          "url": "kohomology-jvm-0.12.jar",
          "size": 1719179,
          "sha512": "9b0f37c139d51a2c1783a1dfc6f0d2f3726a9d27256d572761243f0f0cb05c0f0ffcdc921240e0dccb80f0863c7baac6689f4c6bd39cdfe0a1eca3dde337342a",
          "sha256": "33b97973215f2b1a771f3951e838493e73433ad62abb54a3b1f43abae566d0e6",
          "sha1": "b5f0b26f418d0e687f3b48b52c6f2ce6df830a46",
          "md5": "8f66f408f291c894495b38d13d177adb"
        }
      ]
    }
  ]
}
