{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug/0.2/kococo-debug-0.2.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jvm-0.2.jar",
          "url": "kococo-debug-jvm-0.2.jar",
          "size": 1647,
          "sha512": "9040ca780efc5587dd8bb2c8f10ebce10ea7c26c3b2cc08886c41c30fca3e4dee401f7107907c803bac56aa5b534705e9efc163eb80a4a345c02086d3491df2a",
          "sha256": "1a350f56261dbb7f706504cf128372107d09032f71257c5d8de815dc9331310b",
          "sha1": "95231e5b5b761ddfbe5d3b6c55304151709812ae",
          "md5": "06d3a9075215b3f2517cb387bcd81466"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug-jvm-0.2.jar",
          "url": "kococo-debug-jvm-0.2.jar",
          "size": 1647,
          "sha512": "9040ca780efc5587dd8bb2c8f10ebce10ea7c26c3b2cc08886c41c30fca3e4dee401f7107907c803bac56aa5b534705e9efc163eb80a4a345c02086d3491df2a",
          "sha256": "1a350f56261dbb7f706504cf128372107d09032f71257c5d8de815dc9331310b",
          "sha1": "95231e5b5b761ddfbe5d3b6c55304151709812ae",
          "md5": "06d3a9075215b3f2517cb387bcd81466"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kococo-debug-jvm-0.2-sources.jar",
          "url": "kococo-debug-jvm-0.2-sources.jar",
          "size": 556,
          "sha512": "5619406db31fe030e4b48022e09ad8dd9e211012ecf689ce4e9474fa57acc4d7f1c9dc7ff6a4c61ab0dea661be6fed484d0c9cb11eafaae2e4dae62556427048",
          "sha256": "c3d362ff76f34b2a3cbfcad9acf8ab1af9aebc37aa2d6f090242e7045f3d83b3",
          "sha1": "65a46aa47f64868c9b9898e3bbfca3c018844238",
          "md5": "6a2604c9ddbd1c7a6dfa177a129d3adc"
        }
      ]
    }
  ]
}
