{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotex/0.1/kotex-0.1.module",
    "group": "me.shun",
    "module": "kotex",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "kotex-jvm-0.1.jar",
          "url": "kotex-jvm-0.1.jar",
          "size": 33641,
          "sha512": "0ab8c5b40a3c41254e5da357f0fc0687d882e4fe4f7fcbc5281bce206f5b7fe454e1a5599ae42fdefff8c64689809c4b6a8cf043ef150c11f7dc0c8fc1d47654",
          "sha256": "a6f092f2ad234f6da8abf1f2d42b7549684b79be5ddf50133792b77344fe3f78",
          "sha1": "f6502bdbd84cd8915f986528efd247586b0e7649",
          "md5": "12fc05b7bcca7c046861b320dd02b8bf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.32"
          }
        }
      ],
      "files": [
        {
          "name": "kotex-jvm-0.1.jar",
          "url": "kotex-jvm-0.1.jar",
          "size": 33641,
          "sha512": "0ab8c5b40a3c41254e5da357f0fc0687d882e4fe4f7fcbc5281bce206f5b7fe454e1a5599ae42fdefff8c64689809c4b6a8cf043ef150c11f7dc0c8fc1d47654",
          "sha256": "a6f092f2ad234f6da8abf1f2d42b7549684b79be5ddf50133792b77344fe3f78",
          "sha1": "f6502bdbd84cd8915f986528efd247586b0e7649",
          "md5": "12fc05b7bcca7c046861b320dd02b8bf"
        }
      ]
    }
  ]
}
