{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.8/kohomology-0.8.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.8.klib",
          "size": 580528,
          "sha512": "4d7c5fb2caae1d96f3f7093bc2eb9de9ad453cbcb1e767538743dc652607d5459deb235e382187e3ecea7570d74d3d819901e317ee561d9cabb6e83525dcb6a4",
          "sha256": "51817b50fd81de9909e133f06848ec8da0ebf58b69071332005f099881c8182b",
          "sha1": "d7ca32637f4b8f906baf7d0328fb6fdc71bc5438",
          "md5": "e03226adf7eb5088b5d659f6fde9fbcd"
        }
      ]
    }
  ]
}
