{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.13/kohomology-0.13.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.13.klib",
          "size": 1460491,
          "sha512": "6ae9143a3617d2fd62f195752323626ed76f4b0d51129bc3fbf3035a5d3dc9fa650aa14ea1dbe38ea7adb9e220413250b64c89e22908d6f22b40e50a1d06aaf5",
          "sha256": "993d275eda5613e5a89efd35d20e074f5f64759384a85bf0b062e8d7caba6010",
          "sha1": "7e87edb6bf05e90cc8125941e6e51ff4c49dc5cc",
          "md5": "0c301c59c87df2fdf20c491bc6387b9d"
        }
      ]
    }
  ]
}
