{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.1/kohomology-0.1.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o2x7bm3lqzhkngoogh6vocrekm"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology.klib",
          "url": "kohomology-native-0.1.klib",
          "size": 244939,
          "sha512": "8c91dd3696d5655e2132a47f9cd7d2a01d3f88a52305f7675da18107f82cd98bdefcf41cda7fd00858b34e4c92880a27238169d019482c04b5431a6501e0440d",
          "sha256": "17997c27bc00e8fc990f4474d0c3f4ea32c6426d3d191339d5c876ed3dc56b6c",
          "sha1": "924bad20cf53bbeece1dc83f7cf219d63d2aef1a",
          "md5": "852e4173a5e2b42b1d4f3baf418887e8"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    }
  ]
}
