{
  "formatVersion": "1.1",
  "component": {
    "url": "../../simple-counter/0.1/simple-counter-0.1.module",
    "group": "com.github.shwaka.counter",
    "module": "simple-counter",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "4oqd2ffklvbejajnzvuxlgq65m"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-js-0.1.jar",
          "url": "simple-counter-js-0.1.jar",
          "size": 24229,
          "sha512": "ba78f50d552451f06868ac596cce9cbddb374f8ae5c5df94eab71cfa9a01b798fec26bfa83738bb256480ee668323410d84b95975b7ef81cfd20c8843875cdab",
          "sha256": "acba1ac8f3e40005bc7de49e74da2b337568604af8f0db0ad2d157ffdea569b1",
          "sha1": "e7a08e629541a5c9e859b2c32b3bf6033a965721",
          "md5": "c4e7f2b187be7e20527a61a1aba985de"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-js-0.1.jar",
          "url": "simple-counter-js-0.1.jar",
          "size": 24229,
          "sha512": "ba78f50d552451f06868ac596cce9cbddb374f8ae5c5df94eab71cfa9a01b798fec26bfa83738bb256480ee668323410d84b95975b7ef81cfd20c8843875cdab",
          "sha256": "acba1ac8f3e40005bc7de49e74da2b337568604af8f0db0ad2d157ffdea569b1",
          "sha1": "e7a08e629541a5c9e859b2c32b3bf6033a965721",
          "md5": "c4e7f2b187be7e20527a61a1aba985de"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../simple-counter/0.1/simple-counter-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../simple-counter/0.1/simple-counter-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter",
        "version": "0.1"
      }
    }
  ]
}
