{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.13/kohomology-0.13.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.13.jar",
          "url": "kohomology-js-0.13.jar",
          "size": 530486,
          "sha512": "d6e2f1fd13370de6ea1893c9dc383f67efe44b990ef9fff9f1210a0816314d63e4634ecc187f2b30ff656cce3351a9e8bafef3ed72c04ccd996e90ee38a8e4da",
          "sha256": "5728e90e71d959d23653f1009dea92ec67a96aa4e2c9c933f49b10d73aa08bce",
          "sha1": "969ec0b1a1d53d0621610afd25b4fd1b5e311bfc",
          "md5": "7da8fdfc0e17fea7fe3cfc568bcd9060"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.13.jar",
          "url": "kohomology-js-0.13.jar",
          "size": 530486,
          "sha512": "d6e2f1fd13370de6ea1893c9dc383f67efe44b990ef9fff9f1210a0816314d63e4634ecc187f2b30ff656cce3351a9e8bafef3ed72c04ccd996e90ee38a8e4da",
          "sha256": "5728e90e71d959d23653f1009dea92ec67a96aa4e2c9c933f49b10d73aa08bce",
          "sha1": "969ec0b1a1d53d0621610afd25b4fd1b5e311bfc",
          "md5": "7da8fdfc0e17fea7fe3cfc568bcd9060"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.13.klib",
          "url": "kohomology-js-0.13.klib",
          "size": 1596592,
          "sha512": "3036ed158f9553a1b72d2e79ac78134b8ee12cfc97eec4df5c7ea693bbdea212cbbbfeb35d8d1dec854e94f104cabac5ee5250c763328f78cab93cd19842d83a",
          "sha256": "0fbf57b0f2a177b06d4b6f7e26420ba062aac46aefbe19a8fb8177381f04f92b",
          "sha1": "8aade3d19d49cdfff35c05a23f333296be1c72ff",
          "md5": "ea4a73c9312d167023dbe9ac093ebc8c"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.13.klib",
          "url": "kohomology-js-0.13.klib",
          "size": 1596592,
          "sha512": "3036ed158f9553a1b72d2e79ac78134b8ee12cfc97eec4df5c7ea693bbdea212cbbbfeb35d8d1dec854e94f104cabac5ee5250c763328f78cab93cd19842d83a",
          "sha256": "0fbf57b0f2a177b06d4b6f7e26420ba062aac46aefbe19a8fb8177381f04f92b",
          "sha1": "8aade3d19d49cdfff35c05a23f333296be1c72ff",
          "md5": "ea4a73c9312d167023dbe9ac093ebc8c"
        }
      ]
    }
  ]
}
