{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.1/kohomology-0.1.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o2x7bm3lqzhkngoogh6vocrekm"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.1.jar",
          "url": "kohomology-js-0.1.jar",
          "size": 127634,
          "sha512": "1b1cc836a84f701e46eb12eaf663c0eadf8b38f236473f2ec06d067a5385653d4e34e4ec6036b320d2fe87fbdac076745ced194ec68afdf6e4a80f04ccbf3afc",
          "sha256": "e717cfabb001b07de167073592fb5761e85037dfea17a7fd8ab90def17f6687f",
          "sha1": "6acb2f9938e47be4bf025c880b70387ae30c7288",
          "md5": "916e74475087feda4bf3364e400e24f7"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.1.jar",
          "url": "kohomology-js-0.1.jar",
          "size": 127634,
          "sha512": "1b1cc836a84f701e46eb12eaf663c0eadf8b38f236473f2ec06d067a5385653d4e34e4ec6036b320d2fe87fbdac076745ced194ec68afdf6e4a80f04ccbf3afc",
          "sha256": "e717cfabb001b07de167073592fb5761e85037dfea17a7fd8ab90def17f6687f",
          "sha1": "6acb2f9938e47be4bf025c880b70387ae30c7288",
          "md5": "916e74475087feda4bf3364e400e24f7"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.1.klib",
          "url": "kohomology-js-0.1.klib",
          "size": 257622,
          "sha512": "16a4e36ecb0f94bc41b7fdb9c11a89e8ea45262f3a4f22921eba0181309d857e536e25220c04329c61c1d2a5792174f09af6d87cc2615ab219b3c4fe346106eb",
          "sha256": "4919760f17ba1890290f034de7e62ebebcc530e4c6a94afd781c8075db2838d4",
          "sha1": "081d5ef8a03c6ad5a764139bb295cbd4114e3b28",
          "md5": "efb2379689d16ca677e03a48b851b145"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.1.klib",
          "url": "kohomology-js-0.1.klib",
          "size": 257622,
          "sha512": "16a4e36ecb0f94bc41b7fdb9c11a89e8ea45262f3a4f22921eba0181309d857e536e25220c04329c61c1d2a5792174f09af6d87cc2615ab219b3c4fe346106eb",
          "sha256": "4919760f17ba1890290f034de7e62ebebcc530e4c6a94afd781c8075db2838d4",
          "sha1": "081d5ef8a03c6ad5a764139bb295cbd4114e3b28",
          "md5": "efb2379689d16ca677e03a48b851b145"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.1/kohomology-0.1.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.1"
      }
    }
  ]
}
