{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.11/kohomology-0.11.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.11.jar",
          "url": "kohomology-js-0.11.jar",
          "size": 396529,
          "sha512": "159a98bbf56e3a69a92625cb4b5d352a2566aae1e571e7d3452124485e9234a9a001991ae8749c3677b12b454b631b719db194d286df9e02b3b1077a63ce3c24",
          "sha256": "5158878261812a38c3c8843d031ee5be0b682012f4bf0ab6b181703490183aea",
          "sha1": "cf474f4643c0ee616e8557269ccfdd6f785016e1",
          "md5": "9fd16824764ac2f32e42896412919680"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jslegacy-0.11.jar",
          "url": "kohomology-js-0.11.jar",
          "size": 396529,
          "sha512": "159a98bbf56e3a69a92625cb4b5d352a2566aae1e571e7d3452124485e9234a9a001991ae8749c3677b12b454b631b719db194d286df9e02b3b1077a63ce3c24",
          "sha256": "5158878261812a38c3c8843d031ee5be0b682012f4bf0ab6b181703490183aea",
          "sha1": "cf474f4643c0ee616e8557269ccfdd6f785016e1",
          "md5": "9fd16824764ac2f32e42896412919680"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.11.klib",
          "url": "kohomology-js-0.11.klib",
          "size": 916692,
          "sha512": "51d18f5a2d821bd5dfad6a676396c898f739b666bb1754ca3878e3e126941787b280f90daccc49fc30b79f99e1acae0d23e0b1b3c1e8f55c4985f973d071c402",
          "sha256": "859df187e3901e4c8a4d2f95c97f95bee15f69dba6e39ac2aad4af62e691ca02",
          "sha1": "1e0639c07e058bb98a3b9ee8f804ae9c5084d0a8",
          "md5": "a4a8159576ba2bb413cdabee09f84dc9"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jsir-0.11.klib",
          "url": "kohomology-js-0.11.klib",
          "size": 916692,
          "sha512": "51d18f5a2d821bd5dfad6a676396c898f739b666bb1754ca3878e3e126941787b280f90daccc49fc30b79f99e1acae0d23e0b1b3c1e8f55c4985f973d071c402",
          "sha256": "859df187e3901e4c8a4d2f95c97f95bee15f69dba6e39ac2aad4af62e691ca02",
          "sha1": "1e0639c07e058bb98a3b9ee8f804ae9c5084d0a8",
          "md5": "a4a8159576ba2bb413cdabee09f84dc9"
        }
      ]
    }
  ]
}
