{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.counter",
    "module": "simple-counter",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "zaao2suwlbbi5iwc76kwhyiknu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-metadata-0.1-all.jar",
          "url": "simple-counter-0.1-all.jar",
          "size": 3981,
          "sha512": "c3e4829c7669742241506941069b2660bece55a7c71aa8636cf1ce9a240fbd4ee8fb97ee973f2139b7af7b121ab9b980ff19211997c0029b94597aae11bbdb46",
          "sha256": "a4f4dbee6181e286a9074124ee0cf20e6313952a758ba30cc8a03e706657fe4e",
          "sha1": "a72a2b07a505a2d8b3f8887d87bff5ae53133eb1",
          "md5": "645d22699ed40015e2a7e1105fb1161e"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-0.1.jar",
          "url": "simple-counter-0.1.jar",
          "size": 1780,
          "sha512": "c58c52825cde11a6f4c04316f5062abb01541faf5e5a551361a57397739c51da1552968271c2d17545ae5c3ae2da8dbb5bbf59e2e440108b2c60d9068a3b4978",
          "sha256": "7811bd68e003b05ed948718a83c1d91fbfb99ea80854b75239ff2e5bed40d0da",
          "sha1": "59a0c179e940c7f737e3f2bda2c344d4aecd3791",
          "md5": "35e24d1b2590e59329f390fa91d1ef86"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.1/simple-counter-js-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.1/simple-counter-js-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.1/simple-counter-js-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.1"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.1/simple-counter-js-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../simple-counter-jvm/0.1/simple-counter-jvm-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../simple-counter-jvm/0.1/simple-counter-jvm-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-jvm",
        "version": "0.1"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../simple-counter-native/0.1/simple-counter-native-0.1.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-native",
        "version": "0.1"
      }
    }
  ]
}
