{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.counter",
    "module": "simple-counter",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2rdkvuop2rbwtdcr3vt4a3phe4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-metadata-0.2-all.jar",
          "url": "simple-counter-0.2-all.jar",
          "size": 3981,
          "sha512": "e030967cb9895262d977016358de2ed0006be4d25b2066fdbdf452a11bbe3b6659b1cb38baf04e2826378efa0b8af3a1c3d95b68660b74b17a20ad84ac1d3887",
          "sha256": "b687d6cd9c2b852d084d0f6bfe34869a3eda913fd50bdfad1f55dd9adbd38f23",
          "sha1": "9a8837ce826fbd86c032b6d15cbab69116e972cd",
          "md5": "b4b30b314c6c72984e5094a1849a5c2f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "simple-counter-0.2.jar",
          "url": "simple-counter-0.2.jar",
          "size": 1780,
          "sha512": "2423e22fff52733cae0eec6a5ebd548523923a20a25fb8d5f8791c1f978fe0a95ee3215b0d8170956b9546b674f56f58c6d8b2c292ab3e76a37d12efe516e814",
          "sha256": "136871e517e2406b728ed00d4a33455a900557a4ebc6dfec3291625f3f711377",
          "sha1": "acfff91e8eb040158282dbbe549e0f86227c41d7",
          "md5": "f9bba474571ced7e9af36ac0042e9bac"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.2/simple-counter-js-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.2/simple-counter-js-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.2/simple-counter-js-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../simple-counter-js/0.2/simple-counter-js-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-js",
        "version": "0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../simple-counter-jvm/0.2/simple-counter-jvm-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../simple-counter-jvm/0.2/simple-counter-jvm-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-jvm",
        "version": "0.2"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../simple-counter-native/0.2/simple-counter-native-0.2.module",
        "group": "com.github.shwaka.counter",
        "module": "simple-counter-native",
        "version": "0.2"
      }
    }
  ]
}
