{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.2/kohomology-0.2.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "z5hav2elabhclfwrfbkestzmy4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.2.jar",
          "url": "kohomology-jvm-0.2.jar",
          "size": 401335,
          "sha512": "f2b257849f24f4b9dd41ec9dec9897b8a7724e8cc7b0bf85186a05b6dd1251c3713c1c04308c8c3fd648f448b40a74b2e913a2a9934fbb44f9f114f2db460917",
          "sha256": "ed0b6888c6df65238b1323054667111bba5a936dbc77a64f0b6e2719b5aa33c5",
          "sha1": "055c7c5264e07620844b7e6ccf70fe45742c7094",
          "md5": "a3ab7eabc13888d474b44f4d00bb90b5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.2.jar",
          "url": "kohomology-jvm-0.2.jar",
          "size": 401335,
          "sha512": "f2b257849f24f4b9dd41ec9dec9897b8a7724e8cc7b0bf85186a05b6dd1251c3713c1c04308c8c3fd648f448b40a74b2e913a2a9934fbb44f9f114f2db460917",
          "sha256": "ed0b6888c6df65238b1323054667111bba5a936dbc77a64f0b6e2719b5aa33c5",
          "sha1": "055c7c5264e07620844b7e6ccf70fe45742c7094",
          "md5": "a3ab7eabc13888d474b44f4d00bb90b5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.2/kohomology-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.2"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kohomology/0.2/kohomology-0.2.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology",
        "version": "0.2"
      }
    }
  ]
}
