{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kococo-debug/0.1/kococo-debug-0.1.module",
    "group": "com.github.shwaka.kococo",
    "module": "kococo-debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "3kcua64d7fclhelwtxr7e6eecm"
    }
  },
  "variants": [
    {
      "name": "native-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kococo-debug.klib",
          "url": "kococo-debug-native-0.1.klib",
          "size": 5289,
          "sha512": "57d9ca0bb08a4d88948df0d3e11a778f74d2106442dae6a3cd09466e94d614cb9f5d83b9b519cdd51f84110d11ac6ced5f25378e06fd5b91a16f9f26a6f123e4",
          "sha256": "a560c11ff34f2d397c6bb85e2fb1436c229d1ce67cec933cdb119aac4cb5cbf6",
          "sha1": "7bade21f1b51f0fa73019fbe9a6099192b3af6f6",
          "md5": "22da9b9f88a891c522dae956e833feb7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kococo-debug-metadata/0.1/kococo-debug-metadata-0.1.module",
        "group": "com.github.shwaka.kococo",
        "module": "kococo-debug-metadata",
        "version": "0.1"
      }
    }
  ]
}
