{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.10-all.jar",
          "url": "kohomology-0.10-all.jar",
          "size": 71003,
          "sha512": "77f31868bb5da3f3f5b5ed2c063ed21fb2e7e17c38d9c1de680097e18b837802be6dc6b14c8149ee5616eb202b5403f940173a6f88a6d78500f1eef990d91c6d",
          "sha256": "65ebc8b56f97de07a054b5b31a49fa8faf5c1c35124df1efe83369bd0f702f23",
          "sha1": "6d830faefbd287f7a3693b8c7b992adaf60aff4e",
          "md5": "65f2e7a214aec3be15f8f94a70facc25"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.10.jar",
          "url": "kohomology-0.10.jar",
          "size": 208188,
          "sha512": "4d5be24d6f66a5fdceed0eb9056a4c049000b0c0062577798103aed9f5456b7cc3d20a3b502e0c0af64f6810ef8810ff64a61f2364efb13ee9050437d1b724d2",
          "sha256": "6ca22ffdffc8a8d12bff487f8a94ceeb08fe0c96f02e3b67984469c87fbf72f2",
          "sha1": "948457e6ec310a33e1fe5a4cb525e93145c5576d",
          "md5": "7c60c374146c05f3cff07fe8eaa6ecef"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.10/kohomology-js-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.10"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.10/kohomology-js-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.10"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.10/kohomology-js-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.10"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.10/kohomology-js-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.10"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.10/kohomology-jvm-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.10"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.10/kohomology-jvm-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.10"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.10/kohomology-native-0.10.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.10"
      }
    }
  ]
}
