{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parautil-parallel/0.1/parautil-parallel-0.1.module",
    "group": "com.github.shwaka.parautil",
    "module": "parautil-parallel",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "vkxs7dku7vbefgwnl3o2noj5t4"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "parautil-parallel.klib",
          "url": "parautil-parallel-native-0.1.klib",
          "size": 6493,
          "sha512": "5ed65edb22160f9412e18403c1ce7d437c262ea2009b3c9056f2780040df10e6aa5d3441f8cf7a59e1dcc5f1ccdd6bb5dffcbeab32b69d5260ee10d619baca7e",
          "sha256": "3976df60f813ea83d80c76038918ac2723414004291933e6adaf684eca725c59",
          "sha1": "4dd53e526f1a706fa9d342586cadc82f9cf33bba",
          "md5": "603df90b7d528622a25ef9075b193ef9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-parallel/0.1/parautil-parallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel",
        "version": "0.1"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../parautil-parallel/0.1/parautil-parallel-0.1.module",
        "group": "com.github.shwaka.parautil",
        "module": "parautil-parallel",
        "version": "0.1"
      }
    }
  ]
}
