{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kohomology/0.9/kohomology-0.9.module",
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kohomology-jvm-0.9.jar",
          "url": "kohomology-jvm-0.9.jar",
          "size": 1298843,
          "sha512": "59ae286c166694b5e823582a67e622ecea58ea8ab9081ecc76ad55eaf6a6b082150912d7e3d3c6353372afd0e16d70c44c39a72e8378765c86283959d72433d3",
          "sha256": "656434d72e22499ae26b984b4d4da292f728d216671c36c218ac31fdbca9c7da",
          "sha1": "7f38fff7e6c362de9c1713f21aeca7bf30755d30",
          "md5": "cf0a42085b27d501dfc94a0d6c38e5b9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.github.shwaka.kococo",
          "module": "kococo-release",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.shwaka.counter",
          "module": "simple-counter",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.github.h0tk3y.betterParse",
          "module": "better-parse",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.github.shwaka.parautil",
          "module": "parautil-parallel",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "kohomology-jvm-0.9.jar",
          "url": "kohomology-jvm-0.9.jar",
          "size": 1298843,
          "sha512": "59ae286c166694b5e823582a67e622ecea58ea8ab9081ecc76ad55eaf6a6b082150912d7e3d3c6353372afd0e16d70c44c39a72e8378765c86283959d72433d3",
          "sha256": "656434d72e22499ae26b984b4d4da292f728d216671c36c218ac31fdbca9c7da",
          "sha1": "7f38fff7e6c362de9c1713f21aeca7bf30755d30",
          "md5": "cf0a42085b27d501dfc94a0d6c38e5b9"
        }
      ]
    }
  ]
}
