{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.shwaka.kohomology",
    "module": "kohomology",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "r7wgcldtr5gf5bo7ttwdbubywq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-metadata-0.6-all.jar",
          "url": "kohomology-0.6-all.jar",
          "size": 47913,
          "sha512": "a82ecf04984994d621a7feb2e11841359b57d64e6b145d34dc438560dbcfefd7a04a4f04c7e6e98afc663debdf88c3ea885c9aad9e003c9482d9893ce04a490d",
          "sha256": "2b608d417a60dfb36e565da0487e187640ae16087af6e5e34964a0fdaf34daad",
          "sha1": "1579ff30041540be815395717fbedeb845358c6a",
          "md5": "132e0e6b0792b16442348d624a406ed4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kohomology-0.6.jar",
          "url": "kohomology-0.6.jar",
          "size": 136356,
          "sha512": "5b6ea53a97a67cce5bf86a7d31822a3bb3a4b9c8284b0b58ff7aafd79ffe95ae66fee7b61445a381b8bf83a210de64e9657f472930f5703b065e6b9d92b35a14",
          "sha256": "12f766052c321cb66bc42fe80582d480eddaede1216d6834031011fdd6064bdd",
          "sha1": "ab041f8593967af805f20f32a3d75035b708788a",
          "md5": "40df29f1cebfef27000b13f0fe225bf6"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.6/kohomology-js-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.6"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.6/kohomology-js-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.6"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.6/kohomology-js-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.6"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kohomology-js/0.6/kohomology-js-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-js",
        "version": "0.6"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.6/kohomology-jvm-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.6"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kohomology-jvm/0.6/kohomology-jvm-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-jvm",
        "version": "0.6"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kohomology-native/0.6/kohomology-native-0.6.module",
        "group": "com.github.shwaka.kohomology",
        "module": "kohomology-native",
        "version": "0.6"
      }
    }
  ]
}
